feat: account settings
vojtechsimetka/planuj.finance pull request #237
Opened 2024-11-06 07:14 UTC by hlavkat

2024-11-06 09:35 UTC, vojtechsimetka requested changes

2024-11-06 09:35 UTC, vojtechsimetka commented on src/routes/account/+page.svelte
> +	let passwordChange = $state(false)
Please instead create pages for this:

```
/account/change-email
/account/change-password
```

2024-11-06 09:35 UTC, vojtechsimetka commented on src/lib/components/ui/select/select.svelte
> +		value?: string | null
this should probably be propagated to Diete

2024-11-08 09:25 UTC, agazso commented on src/lib/components/ui/select/select.svelte
> +		value?: string | null
Please don't use `null`, use `undefined` instead

@vojtechsimetka can we make an eslint rule for this?

2024-12-02 18:10 UTC, agazso commented on src/routes/account/+page.svelte
> +			$locale = $locale.split('-')[0]
It does not seem to be a good idea to overwrite a variable that is imported from a library. It would be better to use a local `$state` or `$derived` instead.

2024-12-02 18:29 UTC, agazso approved these changes
Generally works well.

I found minor issues which can be addressed in later PRs:
- The email address field is not `disabled` (because that would change the color). I see that you used the `readonly` property. However this makes the email field to be focused when you click on it and selects all the text. You may want to try to use the `inert` property (see also https://github.com/snaha/diete.design/issues/390)
- If the password is incorrect on the `Change password` page the error is `Invalid credentials`, which I guess was copied from the login page. It is technically not incorrect, but still feels strange here, where it would be better to say `Invalid password`. Please note that on the login page the error is different because we don't want to reveal extra information about the existence of emails or the passwords being incorrect.

2024-12-03 18:10 UTC, agazso commented
After testing a bit more it turns out that the email changing functionality is not working correctly, I opened an [issue about it](#259).

2024-12-03 18:10 UTC, merged